In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
sns.set()

In [3]:
data = pd.read_csv("dataset.csv")
data.head()

,date,continent,grand_prix,circuit,winner_name,team,time,laps,year
0,13-05-1950,Europe,Great Britain,Silverstone Circuit,Nino Farina,Alfa Romeo,2.13.23,70,1950
1,21-05-1950,Europe,Monaco,Circuit de Monaco,Juan Manuel Fangio,Alfa Romeo,3.13.18,100,1950
2,30-05-1950,North America,United States,Indianapolis Motor Speedway,Johnnie Parsons,Kurtis Kraft Offenhauser,2.46.55,138,1950
3,04-06-1950,Europe,Switzerland,Circuit Bremgarten,Nino Farina,Alfa Romeo,2.02.53,42,1950
4,18-06-1950,Europe,Belgium,Circuit de Spa Francorchamps,Juan Manuel Fangio,Alfa Romeo,2.47.26,35,1950